### ISSUE TITLE
Please clarify what is the current status of this project

### ISSUE THREAD

**Issue by eyjohn** [opentracing/opentracing-cpp#123]
I'm interested to know whether there are plans to continue to support/maintain and/or improve this package in-light of recent developments in OpenTelemetry, and if so, for how long and what are the plans for migration if any?

Based on my observation, OpenTelemetry is still in early development, and at this time the C++ implementation is mostly empty/TBD (see https://github.com/open-telemetry/opentelemetry-cpp), so there is value in having a mature tracing implementation available now, and for the near future. 

Furthermore, (based on interactions in OpenTelemetry working groups) there are plans to offer some backwards support for OpenTracing in OpenTelemetry (i.e. you can still use the OpenTracing APIs to instrument your code but the Tracer will forward to OpenTelemetry's SDK), so any further improvements to OpenTracing may still be used in this model.

Can you please share your views/plans with regards to this?

I am interested in contributing to parts of this implementation but did not want to do this if the project is no longer accepting enhancements.

Thanks

**Comment by yurishkuro** [comment]
Most OpenTracing APIs are stable and in maintenance mode; minor fixes are accepted, new features are discouraged. The implementations of the OpenTracing APIs, such as Jaeger clients, are still active because there is currently no production-grade equivalents in the OpenTelemetry. I wrote a blog on the Roadmap for Jaeger implementations: https://medium.com/jaegertracing/jaeger-and-opentelemetry-1846f701d9f2

This C++ repo has traditionally been lacking in maintainers (same as Jaeger C++ client), so there may be more latency in accepting contributions here than in other OT repos.

What enhancements are you interested in? Maybe you could consider contributing them to the opentelemetry-cpp instead?

**Comment by eyjohn** [comment]
Thanks for clarifying the situation.

I was interested in tackling https://github.com/opentracing/opentracing-cpp/issues/97. It'll likely be a stand-alone utility without any changes to existing components.

I can't recall where conversations in the OpenTelemetry project got to with regards to context-propagation, but I imagine the thread local approach in this issue can easily be copied with only some renaming into the OpenTelemetry cpp repo. Unless, the thoughts on context propagation in OpenTelemetry have evolved beyond this, perhaps this discussion is better to continue in https://github.com/opentracing/opentracing-cpp/issues/97.

Thanks again, feel free to close this unless there is anything more you wish to add.

**Comment by yurishkuro** [comment]
The OpenTracing specification provides for context propagation via Scope Managers. It's implemented in many other OT-supported languages.

In OpenTelemetry the context propagation is conceptually similar, but independent of the tracing (see [Context Propagation Layers](https://docs.google.com/document/d/1UxrEYOaQlF_E4gtiPoFmcZ4YKKe1GxohvCvQDuwvD1I/edit).

**Comment by eyjohn** [comment]
Interesting, closing for now to avoid polluting this general question issue further with the specifics, but perhaps you might want to weigh in on the PR/issue.

Thanks for the info/references above
