### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by dansandu** [opentracing/opentracing-cpp#80]
The build fails on Windows because of the following issues:
-  `dlfcn.h` header is not used in `opentracing-cpp/src/dynamic_load.cpp` and this header is not available on Windows
- `cctype` header must be included in `opentracing-cpp/mocktracer/src/tracer_factory.cpp` in order to use `std::isprint` and `std::isspace`

I already have a branch with the fix. If you grant me access I can open a pull request.

**Comment by yurishkuro** [comment]
You don't need any special access. Fork the repo on GitHub, push your branch to your fork, and create PR into main master.

**Comment by yurishkuro** [comment]
If we want to support builds on Windows we would need that as part of the CI. The C# client is using some other CI platform for that.

**Comment by yurishkuro** [comment]
Added https://ci.appveyor.com/project/jaegertracing/jaeger-client-cpp

**Comment by rnburn** [comment]
Could we also add one for just the opentracing-cpp repository?

**Comment by yurishkuro** [comment]
can't... :-(

appvoyor doesn't seem to support organizations, so I named my personal account `jaegertracing`, which results in the project names like `/project/jaegertracing/jaeger-client-cpp`, but if I add any repo-s from opentracing, they will show up under `/project/jaegertracing/` as well.

And I cannot create another account since my account is linked to github account. If someone knows a better way please describe it.

**Comment by rnburn** [comment]
Who created the csharp account: https://ci.appveyor.com/project/opentracing/opentracing-csharp/build/8? It's got the right name.

**Comment by yurishkuro** [comment]
@cwe1ss ^^^ any idea?

**Comment by cwe1ss** [comment]
> @yurishkuro And I cannot create another account since my account is linked to github account. If someone knows a better way please describe it.

The "trick" is to create a completely separate email/password account on the [Sign Up](https://ci.appveyor.com/signup) page and set the desired account name there. You can then add other people as Administrators/Collaborators.

**Comment by rnburn** [comment]
Thanks @cwe1ss - I'll try setting this up next week.

**Comment by yurishkuro** [comment]
> The "trick" is to create a completely separate email/password account on the Sign Up page and set the desired account name there. You can then add other people as Administrators/Collaborators.

@cwe1ss I created a new account with `jaegertracing` name, but still can't find a way to add other users. On the https://ci.appveyor.com/team page if I try to add a new User, it requires a new password, meaning it's not the same user as when I login with my github sso. I also added `jaegertracing/jaeger-maintainers` girthub team, no effect that I can see, i.e. when I login with github account I don't see the projects.

**Comment by cwe1ss** [comment]
@yurishkuro I had the same issues with the opentracing account 😢 .

* The people you want to add first have to log in once to AppVeyor so that their account is created. Then, you have to add them as "Collaborators" instead of "Users" . "Users" [are a weird concept](https://www.appveyor.com/docs/team-setup/#user) in AppVeyor - they can only exist in one account.
* Adding Github teams [doesn't work](https://www.appveyor.com/docs/team-setup/#limitations) if the account is a regular email/password account. For OpenTracing, I added my GitHub user as a Collaborator (with Administrator rights) and tried to add the GitHub team with my Github account but that didn't work either so I had to manually add people as Collaborators.

**Comment by yurishkuro** [comment]
still no joy. I added my github-linked account as collaborator/admin, but it still doesn't show the project

![image](https://user-images.githubusercontent.com/3523016/40272873-21256c52-5b83-11e8-99ed-03151718b46b.png)

I just added you, see if it works.

**Comment by rnburn** [comment]
@yurishkuro - Could you set up the [triggers](https://github.com/opentracing/opentracing-cpp/issues/80#issuecomment-390412188)? It looks like I also don't have access to the settings for the project.

**Comment by yurishkuro** [comment]
done. 

@rnburn you are in the C/C++ Maintainers list, but it was only set to Write, I changed it to Admin, so you should have admin access to the repo as well.

**Comment by cwe1ss** [comment]
@yurishkuro Sorry for not replying earlier - should I still do anything here?
