### ISSUE TITLE
Conventions for ABI changes?

### ISSUE THREAD

**Issue by rnburn** [opentracing/opentracing-cpp#81]
When an app loads a C++ tracer dynamically, all the C++ tracers currently do a comparison of the version of the OT API they were built with to the version of the OT API the app was built with. If there's any difference, they fail with a [incompatible_library_versions_error](https://github.com/opentracing/opentracing-cpp/blob/master/include/opentracing/dynamic_load.h#L70). This is meant to protect against using a tracer and app with incompatible ABIs. Any differences in the ABI can cause the app to segfault.

While this was probably ok behavior to start with, I think it may be too strict as it will cause loading to fail for even minor non-ABI-breaking changes.

I'm wondering if we can establish some conventions for ABI changes to allow for less strict checking.

Perhaps require any ABI change to update at least the minor version of the repository so the comparison can ignore the patch version?

And for reference, these are examples of some changes and how they would affect the ABI:
* Adding, removing, or reordering data members for structs like StartSpanOptions, SpanReference, etc. (Breaks ABI)
* Adding, removing, or reordering  virtual functions. (Breaks ABI).
* Adding a non-virtual function. (Doesn't change ABI).

**Comment by yurishkuro** [comment]
maybe just use https://semver.org/

**Comment by rnburn** [comment]
@yurishkuro - semver is ok to track API changes, but I don't think it's right for ABI versioning. We'd be updating the major version way too often. To give an example, a change like https://github.com/opentracing/opentracing-cpp/pull/56 doesn't break API compatibility but would break ABI compatibility (since it adds a new virtual method).

Another alternative would be to keep separate versioning for the ABI (this is what mongodb does: http://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/api-abi-versioning/).

**Comment by rnburn** [comment]
@isaachier - any thoughts on this?

**Comment by isaachier** [comment]
Sorry I missed this. This might relate to a larger issue in OpenTracing about how to regard changes in the specification that break compatibility with a tracer implementation. For example, recently the spec added a requirement to expose trace ID strings to users. If OpenTracing C++ requires that as a new virtual function, and the Jaeger C++ client does not implement it, I think that represents a breaking ABI change too. Correct me if I'm wrong @tedsuo, I believe the conclusion in one of the OT meetings was to allow this type of change to be represented as a minor version/patch version, not major version change. If that is indeed the case, you should keep the current requirement for exact OT version matching because we cannot say for certain that a new patch version break ABI compatibility or not.

**Comment by rnburn** [comment]
We were discussing versioning the API and ABI separately, passing both to the tracer library to check against, and adding a CI test for ABI breakage.

**Comment by isaachier** [comment]
I understand. The ABI compatibility could just be an integer. It might just be a pain to maintain a separate number.

**Comment by rnburn** [comment]
I actually already have a [number](https://github.com/opentracing/opentracing-cpp/blob/master/CMakeLists.txt#L8) for it but haven't been updating it.

I think adopting something like mongodb's [conventions](http://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/api-abi-versioning/) with a scheme when in development would be good.
